### ISSUE TITLE
Prune old torrents

### ISSUE THREAD

**Issue by DiegoRBaquero** [DiegoRBaquero/uwt#1]
Each swarm has an LRU cache which in some case might never remove peers, consuming RAM. OpenWebTorrent trackers, who's been running without restarting for the longest shows us this, it's full of peers who left ungracefully: https://tracker.openwebtorrent.com/stats

@yciabaud: 

> To fix this, we could implement caching torrents on server to prune old torrents and their swarm to limit memory consumption.
> What do you think?

Taken from https://github.com/feross/bittorrent-tracker/issues/164

**Comment by DiegoRBaquero** [comment]
@yciabaud Fix @1.1.1

**Comment by yciabaud** [comment]
Nice work!
