### ISSUE TITLE
Don't keep track of old torrents

### ISSUE THREAD

**Issue by DiegoRBaquero** [DiegoRBaquero/uwt#4]
In my opinion, there's no point on knowing which infoHashes the tracker has tracked. It just makes the torrents object a huge data structure. Also makes iterating over the infoHashes more resource expensive when the stats are loaded. 

It'd be better if we delete them once the last peer exists. If a new peer rejoins the swarm, it would of course recreate the swarm in the tracker. Only keeping track of active torrents.

@feross @jakefb @alxhotel

**Comment by feross** [comment]
Sounds good to me.

**Comment by DiegoRBaquero** [comment]
Version 1.1.2 delete torrents.

https://github.com/DiegoRBaquero/uwt/blob/64fbe2144833d4502b0ef7eb91102c1a16128c35/index.js#L535

There's still a leak because active < all torrents as seen here: https://tracker.btorrent.xyz/stats

Once fixed, there won't be a difference between all torrents and active torrents in stats and shall be removed.

**Comment by DiegoRBaquero** [comment]
Fixed.

Swarm was being deleted when last peer closed socket. It closes when stopped event is sent to swarm and that's the last peer.

Eviction will cause to check if that's the last peer too.

Released as 1.2.0

**Comment by feross** [comment]
Nice work @DiegoRBaquero 👏
