### ISSUE TITLE
MAJOR: Remove "all/active" torrents stats

### ISSUE THREAD

**Issue by DiegoRBaquero** [DiegoRBaquero/uwt#6]
As there are only active torrents now, stats should only show the # of active torrents.

imo 'activeTorrents' should be gone and 'torrents' should be kept.

@jakefb @alxhotel @yciabaud @feross

**Comment by yciabaud** [comment]
I agree with you, I don't see the benefit of keeping track of "inactive" torrents anyway.

**Comment by alxhotel** [comment]
Agreed. It should be removed.

I'm a bit confused, are we going to use this in `bittorrent-tracker` or is it only for `uwt`?

**Comment by feross** [comment]
We should work on getting all the `uwt` changes upstreamed into `bittorrent-tracker`. Happy to help with reviews to make that happen.
